# Generated by Django 3.2 on 2021-04-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('pincode', models.CharField(default=None, max_length=8)),
                ('landmark', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NGOModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('banner_image_url', models.CharField(default=None, max_length=200, null=True)),
                ('admin_name', models.CharField(default=None, max_length=100)),
                ('contact_number', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=200)),
                ('password', models.CharField(default=None, max_length=100)),
                ('website_url', models.CharField(default=None, max_length=200, null=True)),
                ('login_uname', models.CharField(default=None, max_length=100, null=True)),
                ('latitude', models.CharField(default=None, max_length=50, null=True)),
                ('longitude', models.CharField(default=None, max_length=50, null=True)),
                ('ngo_type', models.CharField(default=None, max_length=50, null=True)),
                ('activation_status', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationAndVerification.addressmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200)),
                ('email', models.CharField(default=None, max_length=200)),
                ('contact_number', models.CharField(default=None, max_length=200)),
                ('pre_latitude', models.CharField(default=None, max_length=50, null=True)),
                ('pre_longitude', models.CharField(default=None, max_length=50, null=True)),
                ('points', models.CharField(default=None, max_length=50, null=True)),
                ('activation_status', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('NGO_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationAndVerification.ngomodel')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationAndVerification.addressmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('donor_type', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200)),
                ('email', models.CharField(default=None, max_length=200)),
                ('contact_number', models.CharField(default=None, max_length=200)),
                ('latitude', models.CharField(default=None, max_length=50, null=True)),
                ('longitude', models.CharField(default=None, max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('activation_status', models.BooleanField(default=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationAndVerification.addressmodel')),
            ],
        ),
    ]
