# Generated by Django 3.2 on 2021-04-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approx_weight', models.IntegerField(default=None)),
                ('num_people', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=200)),
                ('area', models.CharField(default=None, max_length=200)),
                ('contact', models.CharField(default=None, max_length=12)),
                ('ngo_username', models.CharField(default=None, max_length=200)),
                ('expiration_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(default=None, max_length=10)),
                ('content', models.TextField(default=None)),
                ('packaging', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('pick_up_time', models.TimeField(default=None)),
                ('dead_time', models.TimeField(default=None)),
                ('status', models.CharField(default=None, max_length=100)),
                ('receiver', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(default=None, max_length=20)),
                ('destination', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.requestlocation')),
                ('food_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.foodmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(default=None, max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default=None, max_length=400)),
                ('post_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.postmodel')),
            ],
        ),
    ]
