# Generated by Django 3.2 on 2021-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='location_url',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='location_url',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='num_people',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='receiver',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
